/*
 * This file is generated by jOOQ.
 */
package sos.haruhi.dbframe.jooq.tables.daos;


import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import sos.haruhi.dbframe.jooq.tables.DefineEquipType;
import sos.haruhi.dbframe.jooq.tables.records.DefineEquipTypeRecord;

import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class DefineEquipTypeDao extends DAOImpl<DefineEquipTypeRecord, sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType, String> {

    /**
     * Create a new DefineEquipTypeDao without any configuration
     */
    public DefineEquipTypeDao() {
        super(DefineEquipType.DEFINE_EQUIP_TYPE, sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType.class);
    }

    /**
     * Create a new DefineEquipTypeDao with an attached configuration
     */
    @Autowired
    public DefineEquipTypeDao(Configuration configuration) {
        super(DefineEquipType.DEFINE_EQUIP_TYPE, sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType.class, configuration);
    }

    @Override
    public String getId(sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType object) {
        return object.getTypeId();
    }

    /**
     * Fetch records that have <code>type_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfTypeId(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type_id IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByTypeId(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>type_id = value</code>
     */
    public sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType fetchOneByTypeId(String value) {
        return fetchOne(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_ID, value);
    }

    /**
     * Fetch records that have <code>cate_code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfCateCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.CATE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cate_code IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByCateCode(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.CATE_CODE, values);
    }

    /**
     * Fetch records that have <code>cate_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfCateName(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.CATE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cate_name IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByCateName(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.CATE_NAME, values);
    }

    /**
     * Fetch records that have <code>type_code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfTypeCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type_code IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByTypeCode(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_CODE, values);
    }

    /**
     * Fetch records that have <code>type_desc BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfTypeDesc(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_DESC, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type_desc IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByTypeDesc(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_DESC, values);
    }

    /**
     * Fetch records that have <code>type_group BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfTypeGroup(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_GROUP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type_group IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByTypeGroup(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_GROUP, values);
    }

    /**
     * Fetch records that have <code>type_icon BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfTypeIcon(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_ICON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type_icon IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByTypeIcon(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_ICON, values);
    }

    /**
     * Fetch records that have <code>type_major BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfTypeMajor(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_MAJOR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type_major IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByTypeMajor(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_MAJOR, values);
    }

    /**
     * Fetch records that have <code>type_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfTypeName(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type_name IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByTypeName(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_NAME, values);
    }

    /**
     * Fetch records that have <code>version_code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchRangeOfVersionCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(DefineEquipType.DEFINE_EQUIP_TYPE.VERSION_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version_code IN (values)</code>
     */
    public List<sos.haruhi.dbframe.jooq.tables.pojos.DefineEquipType> fetchByVersionCode(String... values) {
        return fetch(DefineEquipType.DEFINE_EQUIP_TYPE.VERSION_CODE, values);
    }
}
