/*
 * This file is generated by jOOQ.
 */
package sos.haruhi.dbframe.jooq.tables.pojos;


import sos.haruhi.dbframe.jooq.tables.interfaces.IGatherReport;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GatherReport implements IGatherReport {

    private static final long serialVersionUID = 1L;

    private String        id;
    private Integer       callNumber;
    private String        dataCode;
    private Long          dataCount;
    private String        dataName;
    private String        dataType;
    private String        deviceId;
    private Integer       gatherCycle;
    private String        gatherIp;
    private LocalDateTime lastTime;
    private LocalDateTime nextTime;

    public GatherReport() {}

    public GatherReport(IGatherReport value) {
        this.id = value.getId();
        this.callNumber = value.getCallNumber();
        this.dataCode = value.getDataCode();
        this.dataCount = value.getDataCount();
        this.dataName = value.getDataName();
        this.dataType = value.getDataType();
        this.deviceId = value.getDeviceId();
        this.gatherCycle = value.getGatherCycle();
        this.gatherIp = value.getGatherIp();
        this.lastTime = value.getLastTime();
        this.nextTime = value.getNextTime();
    }

    public GatherReport(
        String        id,
        Integer       callNumber,
        String        dataCode,
        Long          dataCount,
        String        dataName,
        String        dataType,
        String        deviceId,
        Integer       gatherCycle,
        String        gatherIp,
        LocalDateTime lastTime,
        LocalDateTime nextTime
    ) {
        this.id = id;
        this.callNumber = callNumber;
        this.dataCode = dataCode;
        this.dataCount = dataCount;
        this.dataName = dataName;
        this.dataType = dataType;
        this.deviceId = deviceId;
        this.gatherCycle = gatherCycle;
        this.gatherIp = gatherIp;
        this.lastTime = lastTime;
        this.nextTime = nextTime;
    }

    /**
     * Getter for <code>public.gather_report.id</code>.
     */
    @Override
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.gather_report.id</code>.
     */
    @Override
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.gather_report.call_number</code>.
     */
    @Override
    public Integer getCallNumber() {
        return this.callNumber;
    }

    /**
     * Setter for <code>public.gather_report.call_number</code>.
     */
    @Override
    public void setCallNumber(Integer callNumber) {
        this.callNumber = callNumber;
    }

    /**
     * Getter for <code>public.gather_report.data_code</code>.
     */
    @Override
    public String getDataCode() {
        return this.dataCode;
    }

    /**
     * Setter for <code>public.gather_report.data_code</code>.
     */
    @Override
    public void setDataCode(String dataCode) {
        this.dataCode = dataCode;
    }

    /**
     * Getter for <code>public.gather_report.data_count</code>.
     */
    @Override
    public Long getDataCount() {
        return this.dataCount;
    }

    /**
     * Setter for <code>public.gather_report.data_count</code>.
     */
    @Override
    public void setDataCount(Long dataCount) {
        this.dataCount = dataCount;
    }

    /**
     * Getter for <code>public.gather_report.data_name</code>.
     */
    @Override
    public String getDataName() {
        return this.dataName;
    }

    /**
     * Setter for <code>public.gather_report.data_name</code>.
     */
    @Override
    public void setDataName(String dataName) {
        this.dataName = dataName;
    }

    /**
     * Getter for <code>public.gather_report.data_type</code>.
     */
    @Override
    public String getDataType() {
        return this.dataType;
    }

    /**
     * Setter for <code>public.gather_report.data_type</code>.
     */
    @Override
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * Getter for <code>public.gather_report.device_id</code>.
     */
    @Override
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Setter for <code>public.gather_report.device_id</code>.
     */
    @Override
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Getter for <code>public.gather_report.gather_cycle</code>.
     */
    @Override
    public Integer getGatherCycle() {
        return this.gatherCycle;
    }

    /**
     * Setter for <code>public.gather_report.gather_cycle</code>.
     */
    @Override
    public void setGatherCycle(Integer gatherCycle) {
        this.gatherCycle = gatherCycle;
    }

    /**
     * Getter for <code>public.gather_report.gather_ip</code>.
     */
    @Override
    public String getGatherIp() {
        return this.gatherIp;
    }

    /**
     * Setter for <code>public.gather_report.gather_ip</code>.
     */
    @Override
    public void setGatherIp(String gatherIp) {
        this.gatherIp = gatherIp;
    }

    /**
     * Getter for <code>public.gather_report.last_time</code>.
     */
    @Override
    public LocalDateTime getLastTime() {
        return this.lastTime;
    }

    /**
     * Setter for <code>public.gather_report.last_time</code>.
     */
    @Override
    public void setLastTime(LocalDateTime lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * Getter for <code>public.gather_report.next_time</code>.
     */
    @Override
    public LocalDateTime getNextTime() {
        return this.nextTime;
    }

    /**
     * Setter for <code>public.gather_report.next_time</code>.
     */
    @Override
    public void setNextTime(LocalDateTime nextTime) {
        this.nextTime = nextTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GatherReport (");

        sb.append(id);
        sb.append(", ").append(callNumber);
        sb.append(", ").append(dataCode);
        sb.append(", ").append(dataCount);
        sb.append(", ").append(dataName);
        sb.append(", ").append(dataType);
        sb.append(", ").append(deviceId);
        sb.append(", ").append(gatherCycle);
        sb.append(", ").append(gatherIp);
        sb.append(", ").append(lastTime);
        sb.append(", ").append(nextTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IGatherReport from) {
        setId(from.getId());
        setCallNumber(from.getCallNumber());
        setDataCode(from.getDataCode());
        setDataCount(from.getDataCount());
        setDataName(from.getDataName());
        setDataType(from.getDataType());
        setDeviceId(from.getDeviceId());
        setGatherCycle(from.getGatherCycle());
        setGatherIp(from.getGatherIp());
        setLastTime(from.getLastTime());
        setNextTime(from.getNextTime());
    }

    @Override
    public <E extends IGatherReport> E into(E into) {
        into.from(this);
        return into;
    }
}
