/*
 * This file is generated by jOOQ.
 */
package sos.haruhi.dbframe.jooq.tables.pojos;


import sos.haruhi.dbframe.jooq.tables.interfaces.IUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements IUsers {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private Integer age;
    private String  address;

    public Users() {}

    public Users(IUsers value) {
        this.id = value.getId();
        this.name = value.getName();
        this.age = value.getAge();
        this.address = value.getAddress();
    }

    public Users(
        Integer id,
        String  name,
        Integer age,
        String  address
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.address = address;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    @Override
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.users.id</code>.
     */
    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.users.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.users.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.users.age</code>.
     */
    @Override
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>public.users.age</code>.
     */
    @Override
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Getter for <code>public.users.address</code>.
     */
    @Override
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>public.users.address</code>.
     */
    @Override
    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(address);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUsers from) {
        setId(from.getId());
        setName(from.getName());
        setAge(from.getAge());
        setAddress(from.getAddress());
    }

    @Override
    public <E extends IUsers> E into(E into) {
        into.from(this);
        return into;
    }
}
