/*
 * This file is generated by jOOQ.
 */
package sos.haruhi.dbframe.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDefineEquipType extends Serializable {

    /**
     * Setter for <code>public.define_equip_type.type_id</code>.
     */
    public void setTypeId(String value);

    /**
     * Getter for <code>public.define_equip_type.type_id</code>.
     */
    public String getTypeId();

    /**
     * Setter for <code>public.define_equip_type.cate_code</code>.
     */
    public void setCateCode(String value);

    /**
     * Getter for <code>public.define_equip_type.cate_code</code>.
     */
    public String getCateCode();

    /**
     * Setter for <code>public.define_equip_type.cate_name</code>.
     */
    public void setCateName(String value);

    /**
     * Getter for <code>public.define_equip_type.cate_name</code>.
     */
    public String getCateName();

    /**
     * Setter for <code>public.define_equip_type.type_code</code>.
     */
    public void setTypeCode(String value);

    /**
     * Getter for <code>public.define_equip_type.type_code</code>.
     */
    public String getTypeCode();

    /**
     * Setter for <code>public.define_equip_type.type_desc</code>.
     */
    public void setTypeDesc(String value);

    /**
     * Getter for <code>public.define_equip_type.type_desc</code>.
     */
    public String getTypeDesc();

    /**
     * Setter for <code>public.define_equip_type.type_group</code>.
     */
    public void setTypeGroup(String value);

    /**
     * Getter for <code>public.define_equip_type.type_group</code>.
     */
    public String getTypeGroup();

    /**
     * Setter for <code>public.define_equip_type.type_icon</code>.
     */
    public void setTypeIcon(String value);

    /**
     * Getter for <code>public.define_equip_type.type_icon</code>.
     */
    public String getTypeIcon();

    /**
     * Setter for <code>public.define_equip_type.type_major</code>.
     */
    public void setTypeMajor(String value);

    /**
     * Getter for <code>public.define_equip_type.type_major</code>.
     */
    public String getTypeMajor();

    /**
     * Setter for <code>public.define_equip_type.type_name</code>.
     */
    public void setTypeName(String value);

    /**
     * Getter for <code>public.define_equip_type.type_name</code>.
     */
    public String getTypeName();

    /**
     * Setter for <code>public.define_equip_type.version_code</code>.
     */
    public void setVersionCode(String value);

    /**
     * Getter for <code>public.define_equip_type.version_code</code>.
     */
    public String getVersionCode();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IDefineEquipType
     */
    public void from(IDefineEquipType from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IDefineEquipType
     */
    public <E extends IDefineEquipType> E into(E into);
}
