/*
 * This file is generated by jOOQ.
 */
package sos.haruhi.dbframe.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUsers extends Serializable {

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>public.users.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>public.users.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.users.age</code>.
     */
    public void setAge(Integer value);

    /**
     * Getter for <code>public.users.age</code>.
     */
    public Integer getAge();

    /**
     * Setter for <code>public.users.address</code>.
     */
    public void setAddress(String value);

    /**
     * Getter for <code>public.users.address</code>.
     */
    public String getAddress();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUsers
     */
    public void from(IUsers from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUsers
     */
    public <E extends IUsers> E into(E into);
}
