/*
 * This file is generated by jOOQ.
 */
package sos.haruhi.dbframe.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import sos.haruhi.dbframe.jooq.tables.GatherReport;
import sos.haruhi.dbframe.jooq.tables.interfaces.IGatherReport;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GatherReportRecord extends UpdatableRecordImpl<GatherReportRecord> implements Record11<String, Integer, String, Long, String, String, String, Integer, String, LocalDateTime, LocalDateTime>, IGatherReport {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.gather_report.id</code>.
     */
    @Override
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.gather_report.id</code>.
     */
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.gather_report.call_number</code>.
     */
    @Override
    public void setCallNumber(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.gather_report.call_number</code>.
     */
    @Override
    public Integer getCallNumber() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.gather_report.data_code</code>.
     */
    @Override
    public void setDataCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.gather_report.data_code</code>.
     */
    @Override
    public String getDataCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.gather_report.data_count</code>.
     */
    @Override
    public void setDataCount(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.gather_report.data_count</code>.
     */
    @Override
    public Long getDataCount() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.gather_report.data_name</code>.
     */
    @Override
    public void setDataName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.gather_report.data_name</code>.
     */
    @Override
    public String getDataName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.gather_report.data_type</code>.
     */
    @Override
    public void setDataType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.gather_report.data_type</code>.
     */
    @Override
    public String getDataType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.gather_report.device_id</code>.
     */
    @Override
    public void setDeviceId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.gather_report.device_id</code>.
     */
    @Override
    public String getDeviceId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.gather_report.gather_cycle</code>.
     */
    @Override
    public void setGatherCycle(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.gather_report.gather_cycle</code>.
     */
    @Override
    public Integer getGatherCycle() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.gather_report.gather_ip</code>.
     */
    @Override
    public void setGatherIp(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.gather_report.gather_ip</code>.
     */
    @Override
    public String getGatherIp() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.gather_report.last_time</code>.
     */
    @Override
    public void setLastTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.gather_report.last_time</code>.
     */
    @Override
    public LocalDateTime getLastTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.gather_report.next_time</code>.
     */
    @Override
    public void setNextTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.gather_report.next_time</code>.
     */
    @Override
    public LocalDateTime getNextTime() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, Integer, String, Long, String, String, String, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<String, Integer, String, Long, String, String, String, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return GatherReport.GATHER_REPORT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return GatherReport.GATHER_REPORT.CALL_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return GatherReport.GATHER_REPORT.DATA_CODE;
    }

    @Override
    public Field<Long> field4() {
        return GatherReport.GATHER_REPORT.DATA_COUNT;
    }

    @Override
    public Field<String> field5() {
        return GatherReport.GATHER_REPORT.DATA_NAME;
    }

    @Override
    public Field<String> field6() {
        return GatherReport.GATHER_REPORT.DATA_TYPE;
    }

    @Override
    public Field<String> field7() {
        return GatherReport.GATHER_REPORT.DEVICE_ID;
    }

    @Override
    public Field<Integer> field8() {
        return GatherReport.GATHER_REPORT.GATHER_CYCLE;
    }

    @Override
    public Field<String> field9() {
        return GatherReport.GATHER_REPORT.GATHER_IP;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return GatherReport.GATHER_REPORT.LAST_TIME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return GatherReport.GATHER_REPORT.NEXT_TIME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCallNumber();
    }

    @Override
    public String component3() {
        return getDataCode();
    }

    @Override
    public Long component4() {
        return getDataCount();
    }

    @Override
    public String component5() {
        return getDataName();
    }

    @Override
    public String component6() {
        return getDataType();
    }

    @Override
    public String component7() {
        return getDeviceId();
    }

    @Override
    public Integer component8() {
        return getGatherCycle();
    }

    @Override
    public String component9() {
        return getGatherIp();
    }

    @Override
    public LocalDateTime component10() {
        return getLastTime();
    }

    @Override
    public LocalDateTime component11() {
        return getNextTime();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCallNumber();
    }

    @Override
    public String value3() {
        return getDataCode();
    }

    @Override
    public Long value4() {
        return getDataCount();
    }

    @Override
    public String value5() {
        return getDataName();
    }

    @Override
    public String value6() {
        return getDataType();
    }

    @Override
    public String value7() {
        return getDeviceId();
    }

    @Override
    public Integer value8() {
        return getGatherCycle();
    }

    @Override
    public String value9() {
        return getGatherIp();
    }

    @Override
    public LocalDateTime value10() {
        return getLastTime();
    }

    @Override
    public LocalDateTime value11() {
        return getNextTime();
    }

    @Override
    public GatherReportRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public GatherReportRecord value2(Integer value) {
        setCallNumber(value);
        return this;
    }

    @Override
    public GatherReportRecord value3(String value) {
        setDataCode(value);
        return this;
    }

    @Override
    public GatherReportRecord value4(Long value) {
        setDataCount(value);
        return this;
    }

    @Override
    public GatherReportRecord value5(String value) {
        setDataName(value);
        return this;
    }

    @Override
    public GatherReportRecord value6(String value) {
        setDataType(value);
        return this;
    }

    @Override
    public GatherReportRecord value7(String value) {
        setDeviceId(value);
        return this;
    }

    @Override
    public GatherReportRecord value8(Integer value) {
        setGatherCycle(value);
        return this;
    }

    @Override
    public GatherReportRecord value9(String value) {
        setGatherIp(value);
        return this;
    }

    @Override
    public GatherReportRecord value10(LocalDateTime value) {
        setLastTime(value);
        return this;
    }

    @Override
    public GatherReportRecord value11(LocalDateTime value) {
        setNextTime(value);
        return this;
    }

    @Override
    public GatherReportRecord values(String value1, Integer value2, String value3, Long value4, String value5, String value6, String value7, Integer value8, String value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IGatherReport from) {
        setId(from.getId());
        setCallNumber(from.getCallNumber());
        setDataCode(from.getDataCode());
        setDataCount(from.getDataCount());
        setDataName(from.getDataName());
        setDataType(from.getDataType());
        setDeviceId(from.getDeviceId());
        setGatherCycle(from.getGatherCycle());
        setGatherIp(from.getGatherIp());
        setLastTime(from.getLastTime());
        setNextTime(from.getNextTime());
    }

    @Override
    public <E extends IGatherReport> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GatherReportRecord
     */
    public GatherReportRecord() {
        super(GatherReport.GATHER_REPORT);
    }

    /**
     * Create a detached, initialised GatherReportRecord
     */
    public GatherReportRecord(String id, Integer callNumber, String dataCode, Long dataCount, String dataName, String dataType, String deviceId, Integer gatherCycle, String gatherIp, LocalDateTime lastTime, LocalDateTime nextTime) {
        super(GatherReport.GATHER_REPORT);

        setId(id);
        setCallNumber(callNumber);
        setDataCode(dataCode);
        setDataCount(dataCount);
        setDataName(dataName);
        setDataType(dataType);
        setDeviceId(deviceId);
        setGatherCycle(gatherCycle);
        setGatherIp(gatherIp);
        setLastTime(lastTime);
        setNextTime(nextTime);
    }
}
