/*
 * This file is generated by jOOQ.
 */
package sos.haruhi.dbframe.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import sos.haruhi.dbframe.jooq.tables.DefineEquipType;
import sos.haruhi.dbframe.jooq.tables.GatherReport;
import sos.haruhi.dbframe.jooq.tables.ImpDataDetail;
import sos.haruhi.dbframe.jooq.tables.Users;
import sos.haruhi.dbframe.jooq.tables.records.DefineEquipTypeRecord;
import sos.haruhi.dbframe.jooq.tables.records.GatherReportRecord;
import sos.haruhi.dbframe.jooq.tables.records.ImpDataDetailRecord;
import sos.haruhi.dbframe.jooq.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DefineEquipTypeRecord> DEFINE_EQUIP_TYPE_PKEY = Internal.createUniqueKey(DefineEquipType.DEFINE_EQUIP_TYPE, DSL.name("define_equip_type_pkey"), new TableField[] { DefineEquipType.DEFINE_EQUIP_TYPE.TYPE_ID }, true);
    public static final UniqueKey<GatherReportRecord> GATHER_REPORT_PKEY = Internal.createUniqueKey(GatherReport.GATHER_REPORT, DSL.name("gather_report_pkey"), new TableField[] { GatherReport.GATHER_REPORT.ID }, true);
    public static final UniqueKey<ImpDataDetailRecord> IMP_DATA_DETAIL_PKEY = Internal.createUniqueKey(ImpDataDetail.IMP_DATA_DETAIL, DSL.name("imp_data_detail_pkey"), new TableField[] { ImpDataDetail.IMP_DATA_DETAIL.DATA_ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
}
