/*
 * This file is generated by jOOQ.
 */
package sos.haruhi.dbframe.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import sos.haruhi.dbframe.jooq.tables.DefineEquipType;
import sos.haruhi.dbframe.jooq.tables.GatherReport;
import sos.haruhi.dbframe.jooq.tables.ImpDataDetail;
import sos.haruhi.dbframe.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.define_equip_type</code>.
     */
    public final DefineEquipType DEFINE_EQUIP_TYPE = DefineEquipType.DEFINE_EQUIP_TYPE;

    /**
     * The table <code>public.gather_report</code>.
     */
    public final GatherReport GATHER_REPORT = GatherReport.GATHER_REPORT;

    /**
     * The table <code>public.imp_data_detail</code>.
     */
    public final ImpDataDetail IMP_DATA_DETAIL = ImpDataDetail.IMP_DATA_DETAIL;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DefineEquipType.DEFINE_EQUIP_TYPE,
            GatherReport.GATHER_REPORT,
            ImpDataDetail.IMP_DATA_DETAIL,
            Users.USERS);
    }
}
