/*
 * This file is generated by jOOQ.
 */
package sos.haruhi.dbframe.jooq;


import sos.haruhi.dbframe.jooq.tables.DefineEquipType;
import sos.haruhi.dbframe.jooq.tables.GatherReport;
import sos.haruhi.dbframe.jooq.tables.ImpDataDetail;
import sos.haruhi.dbframe.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.define_equip_type</code>.
     */
    public static final DefineEquipType DEFINE_EQUIP_TYPE = DefineEquipType.DEFINE_EQUIP_TYPE;

    /**
     * The table <code>public.gather_report</code>.
     */
    public static final GatherReport GATHER_REPORT = GatherReport.GATHER_REPORT;

    /**
     * The table <code>public.imp_data_detail</code>.
     */
    public static final ImpDataDetail IMP_DATA_DETAIL = ImpDataDetail.IMP_DATA_DETAIL;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
